# fly.toml app configuration file for ML Power Nowcast Dashboard
#
# Production deployment combining React frontend and Python API
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ml-power-nowcast"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[env]
  NODE_ENV = "production"
  API_PORT = "3000"
  STATIC_DIR = "/app/static"
  S3_BUCKET = "ml-power-nowcast-data-1756420517"
  AWS_DEFAULT_REGION = "us-west-2"

# Health check configuration
[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 3000
    protocol = "http"
    timeout = "5s"
    type = "http"
